export const USER_FETCHING="USER_FETCHING";
export const USER_FETCH_SUCCESS="USER_FETCH_SUCCESS";
export const USER_FETCH_ERROR="USER_FETCH_ERROR";
export const CARD_VISIBILITY="CARD_VISIBILITY";
export const CHANGE_PAGE="CHANGE_PAGE";